version: '3'
services:
  apid:
    build:
      context: .
      dockerfile: ./cmd/apid/Dockerfile
    command: go run cmd/apid/main.go
    env_file:
      - ./common.env
    ports:
      - "7071:8080"
  web:
    build:
      context: .
      dockerfile: ./cmd/web/Dockerfile
    env_file:
      - ./common.env
    ports:
      - "7070:80"
