// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/ipv6/model.proto

package ipv6

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Address struct {
	Network              string   `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Latitude             float64  `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc3f51ce54ad7c89, []int{0}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *Address) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Address) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type Filters struct {
	MinLatitude          float64  `protobuf:"fixed64,1,opt,name=minLatitude,proto3" json:"minLatitude,omitempty"`
	MaxLatitude          float64  `protobuf:"fixed64,2,opt,name=maxLatitude,proto3" json:"maxLatitude,omitempty"`
	MinLongitude         float64  `protobuf:"fixed64,3,opt,name=minLongitude,proto3" json:"minLongitude,omitempty"`
	MaxLongitude         float64  `protobuf:"fixed64,4,opt,name=maxLongitude,proto3" json:"maxLongitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Filters) Reset()         { *m = Filters{} }
func (m *Filters) String() string { return proto.CompactTextString(m) }
func (*Filters) ProtoMessage()    {}
func (*Filters) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc3f51ce54ad7c89, []int{1}
}

func (m *Filters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filters.Unmarshal(m, b)
}
func (m *Filters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filters.Marshal(b, m, deterministic)
}
func (m *Filters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filters.Merge(m, src)
}
func (m *Filters) XXX_Size() int {
	return xxx_messageInfo_Filters.Size(m)
}
func (m *Filters) XXX_DiscardUnknown() {
	xxx_messageInfo_Filters.DiscardUnknown(m)
}

var xxx_messageInfo_Filters proto.InternalMessageInfo

func (m *Filters) GetMinLatitude() float64 {
	if m != nil {
		return m.MinLatitude
	}
	return 0
}

func (m *Filters) GetMaxLatitude() float64 {
	if m != nil {
		return m.MaxLatitude
	}
	return 0
}

func (m *Filters) GetMinLongitude() float64 {
	if m != nil {
		return m.MinLongitude
	}
	return 0
}

func (m *Filters) GetMaxLongitude() float64 {
	if m != nil {
		return m.MaxLongitude
	}
	return 0
}

type ListResult struct {
	Results              []*Address `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListResult) Reset()         { *m = ListResult{} }
func (m *ListResult) String() string { return proto.CompactTextString(m) }
func (*ListResult) ProtoMessage()    {}
func (*ListResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc3f51ce54ad7c89, []int{2}
}

func (m *ListResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResult.Unmarshal(m, b)
}
func (m *ListResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResult.Marshal(b, m, deterministic)
}
func (m *ListResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResult.Merge(m, src)
}
func (m *ListResult) XXX_Size() int {
	return xxx_messageInfo_ListResult.Size(m)
}
func (m *ListResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResult.DiscardUnknown(m)
}

var xxx_messageInfo_ListResult proto.InternalMessageInfo

func (m *ListResult) GetResults() []*Address {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*Address)(nil), "ipv6.Address")
	proto.RegisterType((*Filters)(nil), "ipv6.Filters")
	proto.RegisterType((*ListResult)(nil), "ipv6.ListResult")
}

func init() { proto.RegisterFile("internal/ipv6/model.proto", fileDescriptor_fc3f51ce54ad7c89) }

var fileDescriptor_fc3f51ce54ad7c89 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xb1, 0x4e, 0xc5, 0x20,
	0x14, 0x86, 0x83, 0xf7, 0x46, 0xbc, 0xe7, 0xea, 0xc2, 0x84, 0xc6, 0x81, 0xb0, 0xd8, 0xa9, 0x37,
	0xd1, 0xe8, 0xee, 0xe2, 0xd4, 0x89, 0xdd, 0x01, 0x03, 0x31, 0x44, 0x0a, 0x0d, 0x9c, 0x6a, 0x5f,
	0xc4, 0xf7, 0x35, 0xc5, 0xd6, 0xb6, 0x6e, 0x9c, 0xef, 0xff, 0x38, 0x27, 0xf9, 0xe1, 0xda, 0x05,
	0xb4, 0x29, 0x68, 0x7f, 0x72, 0xdd, 0xe7, 0xd3, 0xa9, 0x8d, 0xc6, 0xfa, 0xba, 0x4b, 0x11, 0x23,
	0xdb, 0x8f, 0x44, 0xbe, 0x02, 0x7d, 0x36, 0x26, 0xd9, 0x9c, 0x19, 0x07, 0x1a, 0x2c, 0x7e, 0xc5,
	0xf4, 0xc1, 0x89, 0x20, 0xd5, 0x41, 0xcd, 0x23, 0xbb, 0x81, 0x0b, 0xaf, 0xd1, 0x61, 0x6f, 0x2c,
	0x3f, 0x13, 0xa4, 0x22, 0xea, 0x6f, 0x66, 0xb7, 0x70, 0xf0, 0x31, 0xbc, 0xff, 0x86, 0xbb, 0x12,
	0x2e, 0x40, 0x7e, 0x13, 0xa0, 0x2f, 0xce, 0xa3, 0x4d, 0x99, 0x09, 0x38, 0xb6, 0x2e, 0x34, 0xf3,
	0x22, 0x52, 0xdc, 0x35, 0x2a, 0x86, 0x1e, 0x9a, 0xed, 0xa9, 0x35, 0x62, 0x12, 0x2e, 0xc7, 0x0f,
	0xff, 0x0e, 0x6e, 0x58, 0x71, 0xf4, 0xb0, 0x38, 0xfb, 0xc9, 0x59, 0x31, 0xf9, 0x08, 0xd0, 0xb8,
	0x8c, 0xca, 0xe6, 0xde, 0x23, 0xbb, 0x03, 0x9a, 0xca, 0x2b, 0x73, 0x22, 0x76, 0xd5, 0xf1, 0xfe,
	0xaa, 0x1e, 0xcb, 0xa9, 0xa7, 0x66, 0xd4, 0x9c, 0xbe, 0x9d, 0x97, 0xea, 0x1e, 0x7e, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x7a, 0xba, 0xe7, 0x7f, 0x57, 0x01, 0x00, 0x00,
}
